[book]
authors = []
language = "en"
src = "src"
title = "VRobots Book"

[preprocessor.tabs]

[output.html]
site-url = "/vrobots-book/"
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]
